@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Sep 27 14:38:52 +0530 2024
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim SMMS_bus_tb_behav -key {Behavioral:sim_1:Functional:SMMS_bus_tb} -tclbatch SMMS_bus_tb.tcl -view C:/Users/Hansa Niluka/OneDrive - University of Moratuwa/semster 07/4.EN4021 - Advanced Digital Systems/Bus-Desingn/Simple_bus_SMMS/SMMS_bus_tb_behav_sucessfull.wcfg -log simulate.log"
call xsim  SMMS_bus_tb_behav -key {Behavioral:sim_1:Functional:SMMS_bus_tb} -tclbatch SMMS_bus_tb.tcl -view C:/Users/Hansa Niluka/OneDrive - University of Moratuwa/semster 07/4.EN4021 - Advanced Digital Systems/Bus-Desingn/Simple_bus_SMMS/SMMS_bus_tb_behav_sucessfull.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
